export const POSSIBLE_CARD_TYPES = ["VISA", "MAESTRO", "MASTERCARD", "AMEX", "DISCOVER", "DINERSCLUB", "JCB", "CUP", "CARTESBANCAIRES", "CARNET"];
export const DEFAULT_CARD_TYPES = ["VISA", "MASTERCARD"];
